// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Usar DIRECT_URL para migraciones/CLI porque el pooler de Neon
    // no soporta bien prepared statements y mantiene conexiones abiertas.
    // El runtime de la app sigue usando DATABASE_URL (pooled) vía src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
